export const hallIdentities = {
    "Sir Ashutosh Mukherjee Hall": { short: "AM", emoji: "🏛️" },
    "Azad Hall of Residence": { short: "Azad", emoji: "🦅" },
    "B C Roy Hall of Residence": { short: "BCR", emoji: "🏥" },
    "B R Ambedkar Hall of Residence": { short: "BRA", emoji: "⚖️" },
    "Gokhale Hall of Residence": { short: "Gokhale", emoji: "📖" },
    "Homi J Bhabha Hall of Residence": { short: "HJB", emoji: "⚛️" },
    "Jagadish Chandra Bose Hall of Residence": { short: "JCB", emoji: "🔬" },
    "Lal Bahadur Shastri Hall of Residence": { short: "LBS", emoji: "🌾" },
    "Lala Lajpat Rai Hall of Residence": { short: "LLR", emoji: "🔥" },
    "Madan Mohan Malviya Hall of Residence": { short: "MMM", emoji: "📚" },
    "Meghnad Saha Hall of Residence": { short: "MS", emoji: "🔬" },
    "Mother Teresa Hall of Residence": { short: "MT", emoji: "🕊️" },
    "Nehru Hall of Residence": { short: "Nehru", emoji: "🌹" },
    "Patel Hall of Residence": { short: "Patel", emoji: "🗽" },
    "Radha Krishnan Hall of Residence": { short: "RK", emoji: "🪖" },
    "Rani Laxmibai Hall of Residence": { short: "RLB", emoji: "⚔️" },
    "Rajendra Prasad Hall of Residence": { short: "RP", emoji: "📜" },
    "Sarojini Naidu - Indira Gandhi Hall of Residence": { short: "SNIG", emoji: "🌟" },
    "Sister Nivedita Hall of Residence": { short: "SNH", emoji: "🌸" },
    "Vidyasagar Hall of Residence": { short: "VS", emoji: "🎓" },
    "Zakir Hussain Hall of Residence": { short: "ZH", emoji: "🎼" },
    "Default": { short: "Hall", emoji: "🏢" }
};
